### ISSUE TITLE
Running `docker compose up` yields error "self-signed certificate in certificate chain"

### ISSUE THREAD

**Issue by GuyHoozdis** [dockersamples/kafka-development-node#2]
# What Should Happen

As the `README` instructs, running `docker compose up` should build the images described in `compose.yaml` and run the containers based on those images.

# What Happened Instead

Upon running `docker compose up`, an error is encountered.

> Error: self-signed certificate in certificate chain

# Steps to Reproduce

1. Clone the repo.
2. `cd` in to the repo directory.
3. Bring up the containerized services w/ `docker compose up`
4. Notice the error and containerized services are not running.

```
$ docker compose up
[+] Running 18/18

# ... snip...

[+] Building 1.4s (9/10)                                                                                          docker:desktop-linux

# ... snip...

 => CACHED [app dev 1/3] COPY app/package.json app/yarn.lock ./                                                                   0.0s
 => ERROR [app dev 2/3] RUN yarn install && yarn cache clean                                                                      0.6s
------
 > [app dev 2/3] RUN yarn install && yarn cache clean:
0.201 yarn install v1.22.22
0.216 [1/4] Resolving packages...
0.228 [2/4] Fetching packages...
0.458 error Error: self-signed certificate in certificate chain
0.458     at TLSSocket.onConnectSecure (node:_tls_wrap:1677:34)
0.458     at TLSSocket.emit (node:events:519:28)
0.458     at TLSSocket._finishInit (node:_tls_wrap:1076:8)
0.458     at ssl.onhandshakedone (node:_tls_wrap:862:12)
0.458 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
failed to solve: process "/bin/sh -c yarn install && yarn cache clean" did not complete successfully: exit code: 1
```

**Comment by mikesir87** [comment]
Hi @GuyHoozdis! Out of curiosity, are you on a work machine that might have its traffic proxies through an HTTPS proxy? Based on the error, it suggests the self-signed cert error is being hit when trying to download the Yarn dependencies.

**Comment by GuyHoozdis** [comment]
> Hi @GuyHoozdis! Out of curiosity, are you on a work machine that might have its traffic proxies through an HTTPS proxy? Based on the error, it suggests the self-signed cert error is being hit when trying to download the Yarn dependencies.

I just came across an [SO Post](https://stackoverflow.com/a/40225845) that said the same thing!

Thanks for the quick reply @mikesir87.  Yes, that is indeed my scenario.  I think I know what to do now.

Thanks!
